use std::path::PathBuf;

use ts_rs::TS;

#[allow(dead_code)]
#[path = "src/models.rs"]
mod models;

fn main() {
    generate_typescript_bindings().expect("failed to generate TypeScript bindings");
    tauri_build::build()
}

fn generate_typescript_bindings() -> Result<(), Box<dyn std::error::Error>> {
    let mut output = String::from("// @generated by src-tauri/build.rs. Do not edit manually.\n\n");

    push_exported_decl::<models::MonitorStats>(&mut output);
    push_exported_decl::<models::MonitorStatus>(&mut output);
    push_exported_decl::<models::CurrentActivity>(&mut output);
    push_exported_decl::<models::SessionRow>(&mut output);
    push_exported_decl::<models::UsageRow>(&mut output);

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let generated_dir = manifest_dir.join("../src/lib/generated");
    std::fs::create_dir_all(&generated_dir)?;
    std::fs::write(generated_dir.join("models.ts"), output)?;

    println!("cargo:rerun-if-changed=src/models.rs");
    println!("cargo:rerun-if-changed=build.rs");

    Ok(())
}

fn push_exported_decl<T: TS>(output: &mut String) {
    let decl = T::decl();
    if let Some(stripped) = decl.strip_prefix("type ") {
        output.push_str("export type ");
        output.push_str(stripped);
    } else if let Some(stripped) = decl.strip_prefix("interface ") {
        output.push_str("export interface ");
        output.push_str(stripped);
    } else {
        output.push_str("export ");
        output.push_str(&decl);
    }
    output.push_str("\n\n");
}
